service: workflow-lambda

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  stage: dev
  timeout: 15
  runtime: nodejs18.x
  region: us-east-1

functions:

  getProjectsUsecaseOverview:
    handler: dashboard/getProjectsUsecaseOverview.handler 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /projects_usecase_overview
        method: get
        cors: true

  addWorkflowToProject:
    handler: project/addWorkflowToProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /project/workflow/new
          method: put     
          cors : true
          request:
            schemas:
              application/json: ${file(models\add_workflow.json)}  

  allresources:
    handler: getallresources.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /allresource
        method: get

  allresourcesbyfilter:
    handler: getallresourcebyfilter.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /allresourcebyfilter
        method: get

  getOrgProjectsOverview:
    handler: dashboard/getOrgProjectsOverview.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /org_projects_overview
          method: get
  
  # allProject
  getProjects:
    handler: project/getProjects.handler 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /project
        method: get
        cors: true

  getResources:
    handler: resource/getResources.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /resource
          method: get
          cors: true

  getProjectsOverview:
    handler: dashboard/getProjectsOverview.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /projects_overview
          method: get
          cors: true    

  getResourcesTasksStatus:
    handler: dashboard/getResourcesTasksStatus.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /resources_task_status
        method: get
        cors: true

  getProjectsUsecases:
    handler: project/getProjectsUsecases.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path:  /project/usecase/all
        method: get
        cors: true 

  getProjectsUsecaseByName:
    handler: project/getProjectsUsecaseByName.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /project/usecase/{name}
        method: get
        cors: true 

  usecase_search:
    handler: usecase/usecase_search.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /searchusecase
        method: get
        cors: true 

  addTeamToProject:
    handler: project/addTeamToProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /project/team/new
        method: put
        cors: true
        request:
            schemas:
              application/json: ${file(models/addTeamToProject.json)}
        
  delete_usecase:
    handler: project/delete_usecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /project/usecase/delete
        method: delete
        cors: true

##searchbargetresourcebyname
  getResourcesByName:
    handler: misc/getResourcesByName.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /get_resource_by_name
        method: get
        cors: true
  
  # addProject
  addProject:
    handler: project/addProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /Project
        method: post
        cors: true
        request:
            schemas:
              application/json: ${file(models/addProject.json)}
  #addusecase
  addusecase:
    handler: project/addusecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /project/usecase/new
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(models\add_usecase.json)}
  # stages
  getAllWorkflows:
    handler: project/getAllWorkflows.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /project/workflow/all
        method: get
        cors: true
  #assignStage
  assignStage:
    handler: project/assignStage.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /project/usecase/assign_stage
          method: put
          cors: true
  addStage:
    handler: /project/addStage.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /project/{usecase_id}/stage
        method: put
        cors: true        
        request:
            schemas:
              application/json: ${file(models/addStage.json)}

  getTaskDetails:
    handler: task/getTaskDetails.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /task/details
        method: get
        cors: true 

  startTask:
    handler: task/startTask.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /task/{task_id}/start
          method: put
          cors: true

  getResourcesByRole:
    handler: misc/getResourcesByRole.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /get_resource_by_role
          method: get
          cors: true

  assignTask:
    handler: project/assignTask.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /project/usecase/assign_task
          method: put
          cors: true

  deleteProject:
    handler: delete/deleteProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /deleteProject
          method: delete
          cors: true   

  DeleteStageFromUsecase:
    handler: usecase/DeleteStageFromUsecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /deleteStage
          method: delete
          cors: true
  addresource :
    handler: resource/addresource.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - http:
          path: /resource
          method: post
          cors: true           
          
