service: workflow-lambda

frameworkVersion: "3"

useDotenv: true

plugins:
    - serverless-offline

provider:
    name: aws
    stage: dev
    timeout: 15
    runtime: nodejs18.x
    region: us-east-1
    cors:
        origin: '*'

functions: 
    - ${file(./project/function.yml)}
    - ${file(./workflow/function.yml)}
    - ${file(./usecase/function.yml)}
    - ${file(./dashboard/function.yml)}
    - ${file(./task/function.yml)}
    - ${file(./resource/function.yml)}

custom:
  http:
    cors:
      origin: '*' # Allow requests from any origin
      methods: ['OPTIONS', 'POST', 'PUT']    