service: workflow-lambda

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  stage: dev
  timeout: 15
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    payload: "2.0"
    disableDefaultEndpoint: true
    cors: true

functions:

  getProjectOverview:
    handler: dashboard/getProjectOverview.handler 
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project_usecase_overview
        method: get
      

  getAllProjectsOverview:
    handler: dashboard/getAllProjectsOverview.handler 
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /projects_usecase_overview
        method: get
        

  addWorkflowToProject:
    handler: project/addWorkflowToProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /project/workflow/new
          method: put     

  allresources:
    handler: getallresources.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /allresource
        method: get

  allresourcesbyfilter:
    handler: getallresourcebyfilter.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /allresourcebyfilter
        method: get

  getOrgProjectDetails:
    handler: dashboard/getOrgProjectDetails.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /org_projects_overview
          method: get

  getOrgAllProjectStatusDetails:
    handler: dashboard/getOrgAllProjectStatusDetails.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /org_projects_status_overview
          method: get
  
  # allProject
  getProjects:
    handler: project/getProjects.handler 
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project
        method: get
        

  getResources:
    handler: resource/getResources.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /resource
          method: get
          

  getProjectsOverview:
    handler: dashboard/getProjectsOverview.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /projects_overview
          method: get
              

  getResourcesTasksStatus:
    handler: dashboard/getResourcesTasksStatus.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /resouce_task_status
        method: get
        
 
  getAllResourcesTasksStatus:
    handler: dashboard/getAllResourcesTasksStatus.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /resources_task_status
        method: get
            

  getProjectsUsecases:
    handler: project/getProjectsUsecases.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path:  /project/usecase/all
        method: get
         

  getProjectsUsecaseByName:
    handler: project/getProjectsUsecaseByName.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project/usecase/{name}
        method: get
         

  usecase_search:
    handler: usecase/usecase_search.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /searchusecase
        method: get
         

  addTeamToProject:
    handler: project/addTeamToProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project/team/new
        method: put
        
        
  delete_usecase:
    handler: project/delete_usecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project/usecase/delete
        method: delete
        

##searchbargetresourcebyname
  getResourcesByName:
    handler: misc/getResourcesByName.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /get_resource_by_name
        method: get
        
  
  # addProject
  addProject:
    handler: project/addProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /Project
        method: post
        
  #addusecase
  addusecase:
    handler: project/addusecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /project/usecase/new
          method: post
          
  # stages
  stageDetailsForCreatingUsecase:
    handler: project/stageDetailsForCreatingUsecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project/workflow/all
        method: get
        
  #assignStage
  assignStage:
    handler: project/assignStage.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /project/usecase/assign_stage
          method: put
          
  addStage:
    handler: /project/addStage.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /project/{usecase_id}/stage
        method: put
                
  
  getTaskDetails:
    handler: task/getTaskDetails.handler
    role: ${env:LAMBDA_ROLE}
    events:
    - httpApi:
        path: /task/details
        method: get
         

  startTask:
    handler: task/startTask.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /task/start
          method: put
          

  getResourcesByRole:
    handler: misc/getResourcesByRole.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /get_resource_by_role
          method: get
          

  assignTask:
    handler: project/assignTask.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /project/usecase/assign_task
          method: put
          

  deleteProject:
    handler: delete/deleteProject.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /deleteProject
          method: delete
             

  DeleteStageFromUsecase:
    handler: usecase/DeleteStageFromUsecase.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /deleteStage
          method: delete
          
  addresource :
    handler: resource/addresource.handler
    role: ${env:LAMBDA_ROLE}
    events:
      - httpApi:
          path: /resource
          method: post
                     
          
