openapi: 3.0.3 
info:
  title: Workflow Managemant Specification
  version: 1.0.0
  description: Workflow Managemant API specification

servers:
  - url: '{protocol}://{ip}:{port}/{base-api}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      ip:
        enum:
          - localhost
          - 34.199.12.114
        default: localhost
      port:
        enum:
          - '9000'
          - '5057'
        default: '9000'
      base-api:
        enum:
          - api
        default: api
tags: 
  - name: projects
    description: perform CRUD operations on projects Table
paths:
  /projects/{projectId}/usecases:
    parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
          description: The ID of the project
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            format: date
          description: The start date for filtering use cases
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            format: date
          description: The end date for filtering use cases
    get:
      tags: 
        - Projects
      summary: get usecases details of a specific Projects
      operationId: getProject
      responses:
        200:
          description: Successful response
        400:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /projects/usecases:
    parameters:
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            format: date
          description: The start date for filtering use cases
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            format: date
          description: The end date for filtering use cases
    get:
      tags: 
        - Projects
      summary: get all projects
      operationId: getProjects
      responses:
        200:
          description: Successful response
        400:
          description: "Service Not found"
        500:
          description: "Internal Server Error"